name: Run Tests

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Cache node modules
              uses: actions/cache@v4
              id: cache
              with:
                  path: node_modules
                  key: npm-packages-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm install

            - name: Run test
              run: npm test
              if: ${{ always() }}
